spring.application.name=sopetran-click

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA}

# Thymeleaf
spring.thymeleaf.cache=false